"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Play, Search, ShieldAlert, Zap, Scale, CheckCircle2, Loader2, MessageSquare, Github, Bot } from "lucide-react";

const DEMO_AGENTS = [
    { id: 1, name: "Context Retriever", icon: Search, color: "#88c0ff", time: 2200, output: "Found 3 similar issues • No duplicates • 2 code owners identified" },
    { id: 2, name: "Architecture Critic", icon: ShieldAlert, color: "#f0a8ff", time: 1600, output: "Score: 8.5/10 • 1 warning • 2 info items • Clean implementation" },
    { id: 3, name: "Impact Quantifier", icon: Zap, color: "#ffcc66", time: 1200, output: "Risk: LOW ✅ • No hotpaths affected • No benchmark regressions" },
    { id: 4, name: "Conflict Resolver", icon: Scale, color: "#66eebb", time: 800, output: "0 conflicts • All reviewers aligned • Consensus: READY TO MERGE" },
];

const MOCK_COMMENT_LINES = [
    "## 🤖 Elastic Pilot — Quality Report for PR #95103",
    "",
    "### 🔍 Triage (Agent 1)",
    "| Check | Result |",
    "|-------|--------|",
    "| Duplicates | ✅ None found |",
    "| Related Issues | 3 similar issues identified |",
    "| Code Owners | @Team:EnterpriseSearch, @sphilipse |",
    "",
    "### 🛡️ Architecture Review (Agent 2)",
    "**Score: 8.5 / 10**",
    "| Severity | Rule | Finding |",
    "|----------|------|---------|",
    "| ⚠️ WARN | Error Handling | Missing try-catch in startup hook |",
    "| ℹ️ INFO | Naming | Index name should use kebab-case |",
    "",
    "### ⚡ Performance Impact (Agent 3)",
    "**Risk Level: LOW** ✅",
    "No performance-critical hotpaths affected.",
    "No benchmark regressions in the last 90 days.",
    "",
    "### ⚖️ Reviewer Consensus (Agent 4)",
    "**Status: ALIGNED** — 0 conflicts detected.",
    "All reviewers agree on the implementation approach.",
    "",
    "---",
    "*Generated by Elastic Pilot in 51.6s • Powered by ELSER v2*",
];

export default function LiveDemo() {
    const [running, setRunning] = useState(false);
    const [activeAgent, setActiveAgent] = useState<number | null>(null);
    const [completed, setCompleted] = useState<Set<number>>(new Set());
    const [typedText, setTypedText] = useState<Record<number, string>>({});
    const [allDone, setAllDone] = useState(false);
    const [showComment, setShowComment] = useState(false);
    const [commentLines, setCommentLines] = useState(0);

    const reset = useCallback(() => {
        setRunning(false);
        setActiveAgent(null);
        setCompleted(new Set());
        setTypedText({});
        setAllDone(false);
        setShowComment(false);
        setCommentLines(0);
    }, []);

    const runDemo = useCallback(async () => {
        reset();
        setRunning(true);

        for (const agent of DEMO_AGENTS) {
            setActiveAgent(agent.id);
            await new Promise((r) => setTimeout(r, agent.time * 0.6));
            const output = agent.output;
            for (let i = 0; i <= output.length; i++) {
                const text = output.slice(0, i);
                setTypedText((prev) => ({ ...prev, [agent.id]: text }));
                await new Promise((r) => setTimeout(r, 12));
            }
            await new Promise((r) => setTimeout(r, 300));
            setCompleted((prev) => new Set([...prev, agent.id]));
        }
        setActiveAgent(null);
        setAllDone(true);
        setRunning(false);

        // Reveal comment line by line
        await new Promise((r) => setTimeout(r, 600));
        setShowComment(true);
        for (let i = 1; i <= MOCK_COMMENT_LINES.length; i++) {
            setCommentLines(i);
            await new Promise((r) => setTimeout(r, 60));
        }
    }, [reset]);

    return (
        <div className="app-card overflow-hidden">
            <div className="app-card-header flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <Play className="h-4 w-4 text-[#88c0ff]" />
                    <span className="text-sm font-bold text-white">Interactive Demo</span>
                    <span className="text-[9px] font-bold uppercase tracking-widest text-[#8ba4c7]">Simulated</span>
                </div>
                <button
                    onClick={runDemo}
                    disabled={running}
                    className="flex items-center gap-2 px-4 py-1.5 rounded-lg text-[11px] font-bold bg-white text-black hover:bg-[#e8f0ff] disabled:opacity-40 disabled:cursor-not-allowed transition-all"
                >
                    {running ? <Loader2 className="h-3 w-3 animate-spin" /> : <Play className="h-3 w-3" />}
                    {running ? "Running..." : allDone ? "Run Again" : "Run Pipeline"}
                </button>
            </div>

            <div className="p-5 space-y-3">
                {DEMO_AGENTS.map((agent) => {
                    const isActive = activeAgent === agent.id;
                    const isDone = completed.has(agent.id);
                    const output = typedText[agent.id] || "";

                    return (
                        <motion.div
                            key={agent.id}
                            animate={{
                                borderColor: isActive ? `${agent.color}66` : isDone ? `${agent.color}33` : "rgba(48,54,61,0.5)",
                                background: isActive ? `${agent.color}08` : "transparent",
                            }}
                            className="rounded-xl border p-4 transition-all"
                        >
                            <div className="flex items-center gap-3 mb-2">
                                <div
                                    className="flex h-8 w-8 items-center justify-center rounded-lg border"
                                    style={{ borderColor: `${agent.color}44`, background: `${agent.color}0d` }}
                                >
                                    {isActive ? (
                                        <Loader2 className="h-4 w-4 animate-spin" style={{ color: agent.color }} />
                                    ) : isDone ? (
                                        <CheckCircle2 className="h-4 w-4" style={{ color: agent.color }} />
                                    ) : (
                                        <agent.icon className="h-4 w-4 text-neutral-600" />
                                    )}
                                </div>
                                <span className={`text-xs font-bold ${isActive || isDone ? "text-white" : "text-neutral-500"}`}>
                                    Agent {agent.id} — {agent.name}
                                </span>
                                {isActive && (
                                    <span className="ml-auto text-[9px] font-black tracking-widest animate-pulse" style={{ color: agent.color }}>
                                        PROCESSING
                                    </span>
                                )}
                                {isDone && (
                                    <span className="ml-auto text-[9px] font-bold tracking-widest text-[#66eebb]">DONE</span>
                                )}
                            </div>
                            {(isActive || isDone) && output && (
                                <motion.div
                                    initial={{ opacity: 0, height: 0 }}
                                    animate={{ opacity: 1, height: "auto" }}
                                    className="ml-11 mt-1"
                                >
                                    <span className="text-[11px] mono-text leading-relaxed" style={{ color: `${agent.color}cc` }}>
                                        {output}
                                        {isActive && <span className="animate-pulse">▌</span>}
                                    </span>
                                </motion.div>
                            )}
                        </motion.div>
                    );
                })}

                {allDone && (
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-center py-3 rounded-xl bg-[#66eebb0d] border border-[#66eebb33]"
                    >
                        <CheckCircle2 className="h-5 w-5 text-[#66eebb] mx-auto mb-1" />
                        <span className="text-xs font-bold text-[#66eebb]">Pipeline Complete — Comment Ready to Post</span>
                    </motion.div>
                )}

                {/* Mock GitHub Comment Preview */}
                <AnimatePresence>
                    {showComment && (
                        <motion.div
                            initial={{ opacity: 0, y: 20, scale: 0.97 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            transition={{ duration: 0.5, ease: "easeOut" }}
                            className="mt-4 rounded-xl border border-[#88c0ff33] overflow-hidden"
                            style={{ background: "linear-gradient(170deg, rgba(15,31,57,0.6) 0%, rgba(7,17,34,0.8) 100%)" }}
                        >
                            {/* Comment header — mimics GitHub */}
                            <div className="flex items-center gap-3 px-4 py-3 border-b border-[#7ea4de22] bg-[#0c1a3088]">
                                <div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#88c0ff15] border border-[#88c0ff33]">
                                    <Bot className="h-3.5 w-3.5 text-[#88c0ff]" />
                                </div>
                                <span className="text-[11px] font-bold text-[#88c0ff]">elastic-pilot</span>
                                <span className="text-[9px] font-bold uppercase tracking-widest text-[#8ba4c7]">bot</span>
                                <span className="text-[10px] text-[#6b7f9e] ml-1">commented just now</span>
                                <div className="ml-auto flex items-center gap-1.5 text-[#6b7f9e]">
                                    <Github className="h-3 w-3" />
                                    <MessageSquare className="h-3 w-3" />
                                </div>
                            </div>

                            {/* Comment body */}
                            <div className="px-5 py-4 mono-text text-[11px] leading-[1.7] max-h-[340px] overflow-y-auto">
                                {MOCK_COMMENT_LINES.slice(0, commentLines).map((line, i) => {
                                    // Heading ##
                                    if (line.startsWith("## ")) {
                                        return <div key={i} className="text-[14px] font-black text-white mt-1 mb-2">{line.replace(/^## /, "")}</div>;
                                    }
                                    if (line.startsWith("### ")) {
                                        return <div key={i} className="text-[12px] font-bold text-[#d3e6ff] mt-3 mb-1">{line.replace(/^### /, "")}</div>;
                                    }
                                    // Table header
                                    if (line.startsWith("|") && line.includes("---")) {
                                        return null; // skip separator
                                    }
                                    if (line.startsWith("|")) {
                                        const cells = line.split("|").filter(Boolean).map((c) => c.trim());
                                        const isHeader = i + 1 < commentLines && MOCK_COMMENT_LINES[i + 1]?.includes("---");
                                        return (
                                            <div key={i} className={`grid gap-2 py-1 px-2 rounded ${isHeader ? "text-[#8ba4c7] text-[9px] font-bold uppercase tracking-wider" : "text-[#c2d6f3]"}`} style={{ gridTemplateColumns: `repeat(${cells.length}, 1fr)` }}>
                                                {cells.map((cell, j) => <span key={j}>{cell}</span>)}
                                            </div>
                                        );
                                    }
                                    // Bold lines
                                    if (line.startsWith("**")) {
                                        return <div key={i} className="text-[11px] font-bold text-white my-1">{line.replace(/\*\*/g, "")}</div>;
                                    }
                                    // HR
                                    if (line === "---") {
                                        return <hr key={i} className="border-[#7ea4de22] my-3" />;
                                    }
                                    // Italic / footer
                                    if (line.startsWith("*") && line.endsWith("*")) {
                                        return <div key={i} className="text-[9px] text-[#6b7f9e] italic mt-2">{line.replace(/^\*|\*$/g, "")}</div>;
                                    }
                                    // Empty line
                                    if (line === "") {
                                        return <div key={i} className="h-2" />;
                                    }
                                    // Normal text
                                    return <div key={i} className="text-[#b6cff3]">{line}</div>;
                                })}
                                {commentLines < MOCK_COMMENT_LINES.length && (
                                    <span className="text-[#88c0ff] animate-pulse">▌</span>
                                )}
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
