import os
import requests
from dotenv import load_dotenv
from tools.diff_parser import fetch_pr_diff, parse_diff_into_chunks, extract_code_patterns

load_dotenv()

AGENT_API_URL = os.getenv("ELASTIC_AGENT_URL")
ELASTIC_API_KEY = os.getenv("ELASTIC_API_KEY")
REPO = os.getenv("GITHUB_REPO")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

HEADERS_GH = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

def get_pr_metadata(pr_number):
    url  = f"https://api.github.com/repos/{REPO}/pulls/{pr_number}"
    resp = requests.get(url, headers=HEADERS_GH)
    resp.raise_for_status()
    return resp.json()

def build_review_prompt(pr_metadata, file_chunks, prior_context=None):
    pr_title  = pr_metadata.get("title", "")
    pr_body   = pr_metadata.get("body", "") or ""
    pr_author = pr_metadata["user"]["login"]
    pr_url    = pr_metadata["html_url"]

    prompt = f"""
You are reviewing this Pull Request:

Title:  {pr_title}
Author: {pr_author}
URL:    {pr_url}

PR Description:
{pr_body[:1000]}
"""

    if prior_context:
        prompt += f"""
---
Context from Prior Agent Analysis (Agent 1 — Context Retriever):
{prior_context[:1500]}

Use the above context to inform your review. If similar issues were found,
check if this PR addresses or repeats the same patterns. If code owners were
identified, note whether the changes align with team ownership boundaries.
---
"""

    prompt += f"""
Code Changes to Review ({len(file_chunks)} files):
"""

    for i, chunk in enumerate(file_chunks):
        hints = extract_code_patterns(chunk["added_code"])
        prompt += f"""
File {i+1}: {chunk['file']}
Static Analysis Hints: {', '.join(hints) if hints else 'None detected'}

Added Code:
```
{chunk['added_code'][:2000]}
```
"""

    prompt += """
---
Instructions:
1. Search the coding standards for each pattern you observe
2. Flag violations with the standard ID, severity, and what to fix
3. For clean code, acknowledge it briefly
4. End with an overall assessment: APPROVE / REQUEST_CHANGES / NEEDS_DISCUSSION
"""
    return prompt.strip()

def call_agent(prompt):
    resp = requests.post(
        AGENT_API_URL,
        headers={
            "Content-Type":  "application/json",
            "Authorization": f"ApiKey {ELASTIC_API_KEY}",
            "kbn-xsrf":     "true"
        },
        json={"input": prompt, "agent_id": "architecture_critic"},
        timeout=300
    )
    if not resp.ok:
        print(f"Agent API error {resp.status_code}: {resp.text[:500]}")
    resp.raise_for_status()
    return resp.json()

def format_review_as_github_comment(agent_response):
    """
    Wrap the agent's response in a GitHub comment template.
    This gets posted directly to the PR.
    """
    return f"""## 🤖 Elastic Contributor Co-pilot — Architecture Review

{agent_response}

---
*This review was generated by the Elastic Contributor Co-pilot using the Elastic Coding Standards index.*
*False positives? Leave a 👎 on this comment and a maintainer will review.*
"""

def post_github_comment(pr_number, comment_body):
    url  = f"https://api.github.com/repos/{REPO}/issues/{pr_number}/comments"
    resp = requests.post(url, headers=HEADERS_GH, json={"body": comment_body})
    resp.raise_for_status()
    print(f"Posted review comment to PR #{pr_number}")
    return resp.json()

def review_pr(pr_number, post_comment=False, prior_context=None):
    print(f"\n{'='*60}")
    print(f"Architecture Critic reviewing PR #{pr_number}")
    print('='*60)

    print("Fetching PR metadata...")
    pr_metadata = get_pr_metadata(pr_number)

    print("Fetching and parsing diff...")
    diff        = fetch_pr_diff(pr_number)
    chunks      = parse_diff_into_chunks(diff)
    print(f"Found {len(chunks)} changed files")

    # Only review files that are likely to have code standards issues
    # Skip docs, configs, and generated files
    reviewable = [
        c for c in chunks
        if any(c["file"].endswith(ext) for ext in [".java", ".py", ".go", ".ts", ".js"])
        and not any(skip in c["file"] for skip in ["generated", "test/resources", ".json"])
    ]
    print(f"Reviewing {len(reviewable)} code files (filtered from {len(chunks)})")

    if not reviewable:
        print("No reviewable code files found in this PR")
        return None

    print("Building review prompt...")
    prompt   = build_review_prompt(pr_metadata, reviewable[:5], prior_context=prior_context)  # cap at 5 files per run

    print("Calling Architecture Critic agent...")
    response = call_agent(prompt)

    # Extract the clean message from agent response
    # API returns: {"response": {"message": "..."}, "steps": [...], ...}
    if "response" in response and isinstance(response["response"], dict):
        review_text = response["response"].get("message", "")
    elif "response" in response and isinstance(response["response"], str):
        review_text = response["response"]
    else:
        review_text = response.get("message", str(response))

    print("\n--- Architecture Critic Report ---")
    print(review_text)

    if post_comment:
        formatted = format_review_as_github_comment(review_text)
        post_github_comment(pr_number, formatted)

    return review_text

if __name__ == "__main__":
    import sys
    pr_number    = int(sys.argv[1]) if len(sys.argv) > 1 else 95103
    post_comment = "--post" in sys.argv

    review_pr(pr_number, post_comment=post_comment)