import os
from dotenv import load_dotenv

load_dotenv()

REPO = os.getenv("GITHUB_REPO")

def compose_welcome_comment(
    username,
    pr_number,
    pr_title,
    similar_issues,
    code_owners,
    relevant_docs,
    is_first_time=True
):
    """
    Compose the full welcome comment.
    Returns a markdown string ready to post to GitHub.
    """

    greeting = f"👋 Welcome to the Elastic project, @{username}!" if is_first_time \
               else f"👋 Thanks for another contribution, @{username}!"

    # Format similar issues section
    def normalize_similar_item(issue):
        # Supports both {"_source": {...}} and plain {"title": ...} formats
        src = issue.get("_source", issue) if isinstance(issue, dict) else {}
        return {
            "number": src.get("number"),
            "title": (src.get("title") or "").strip(),
            "url": src.get("url"),
            "status": src.get("status", "unknown"),
            "type": src.get("type", "issue"),
        }

    if similar_issues:
        similar_section = "### 🔍 Similar Past Issues & PRs\n"
        similar_section += "These might be relevant to your work:\n\n"
        rendered = 0
        for raw_issue in similar_issues:
            issue = normalize_similar_item(raw_issue)
            if issue["number"] is None or not issue["title"] or not issue["url"]:
                continue
            similar_section += (
                f"- [{issue['type'].upper()} #{issue['number']}]({issue['url']}) "
                f"— {issue['title'][:80]} `{issue['status']}`\n"
            )
            rendered += 1
            if rendered >= 3:
                break

        if rendered == 0:
            similar_section = "### 🔍 Similar Past Issues & PRs\nNo closely related issues found. This looks like new ground!\n"
    else:
        similar_section = "### 🔍 Similar Past Issues & PRs\nNo closely related issues found. This looks like new ground!\n"

    # Format code owners section
    if code_owners:
        owners_section = "### 👤 Your Code Reviewers\n"
        owners_section += "Based on the files you changed, these people will review your PR:\n\n"
        for owner in code_owners:
            handle = owner.replace("@", "")
            owners_section += f"- {owner} — feel free to ping them if you have questions\n"
    else:
        owners_section = "### 👤 Your Code Reviewers\nReviewers will be assigned automatically by the team.\n"

    # Format docs section
    if relevant_docs:
        docs_section = "### 📚 Recommended Reading\n"
        docs_section += "Based on the files you changed:\n\n"
        for doc in relevant_docs[:5]:
            docs_section += f"- **[{doc['title']}]({doc['url']})** — {doc['why']}\n"
    else:
        docs_section = ""

    # Assemble the full comment
    comment = f"""## 🤖 Elastic Contributor Co-pilot — Welcome!

{greeting} Thank you for opening PR #{pr_number}: **{pr_title}**

The Elastic Contributor Co-pilot has analyzed your PR and prepared this context report to help you get merged faster.

---

{similar_section}

---

{owners_section}

---

{docs_section}

---

### ✅ Next Steps

1. Make sure your PR description explains **what** changed and **why**
2. Run `./gradlew check` locally before requesting review
3. Check that your tests extend `ESTestCase` (not plain JUnit)
4. If you have questions, ping your code owner above or ask in the [Elastic community forums](https://discuss.elastic.co)

---

### 📊 Code Quality Report

A full architecture and code quality report is being generated and will appear as a follow-up comment in the next minute.

---

*This message was generated by the Elastic Contributor Co-pilot.*
*Something wrong or unhelpful? React with 👎 and a maintainer will review.*
"""
    return comment


def compose_quality_report_comment(pr_number, architecture_review, impact_report):
    """
    The follow-up comment containing the full Agent 2 and Agent 3 output.
    Posted a few seconds after the welcome comment.
    """
    return f"""## 📋 Elastic Contributor Co-pilot — Full Quality Report for PR #{pr_number}

---

### 🏗 Architecture Review

{architecture_review or "_No architecture issues detected. Clean PR!_"}

---

### 📊 Performance Impact Assessment

{impact_report or "_No performance-sensitive modules affected by this change._"}

---

*Reports generated by Elastic Contributor Co-pilot using Elastic Agent Builder, ELSER semantic search, and ES|QL.*
"""
